#!/usr/bin/env python3
"""
Game Boy ROM Chunker for Roblox
Splits Game Boy ROMs into base64-encoded chunks for storage in Roblox
Each chunk is saved as Lua code ready to paste into ModuleScripts

Usage:
    python3 rom_chunker.py <path_to_rom_file> [chunk_size_kb]

Example:
    python3 rom_chunker.py pokemon_red.gb 10
    python3 rom_chunker.py tetris.gb

This will create a folder with all the chunks as Lua files
"""

import os
import sys
import base64
import math

def validate_gb_rom(rom_data):
    """Validate that the file is a Game Boy ROM"""
    if len(rom_data) < 0x150:
        return False, "ROM too small"
    
    # Check cartridge type byte at 0x147
    cart_type = rom_data[0x147]
    valid_types = [
        0x00, 0x01, 0x02, 0x03, 0x05, 0x06, 0x08, 0x09,
        0x0B, 0x0C, 0x0D, 0x0F, 0x10, 0x11, 0x12, 0x13,
        0x15, 0x16, 0x17, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E
    ]
    
    if cart_type not in valid_types:
        return False, f"Unknown cartridge type: 0x{cart_type:02X}"
    
    return True, "Valid Game Boy ROM"

def get_rom_title(rom_data):
    """Extract ROM title from header"""
    if len(rom_data) < 0x144:
        return "Unknown"
    
    title = ""
    for i in range(0x134, 0x144):
        byte = rom_data[i]
        if 32 <= byte < 127:
            title += chr(byte)
        elif byte == 0:
            break
    
    return title.strip() if title else "Unknown"

def split_rom_into_chunks(rom_path, chunk_size_kb=10):
    """
    Split a Game Boy ROM into base64-encoded chunks
    
    Args:
        rom_path: Path to the .gb ROM file
        chunk_size_kb: Size of each chunk in kilobytes
    
    Returns:
        Tuple of (chunks_list, rom_title, total_size, num_chunks)
    """
    
    # Read ROM file
    try:
        with open(rom_path, 'rb') as f:
            rom_data = f.read()
    except FileNotFoundError:
        print(f"Error: ROM file not found: {rom_path}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading ROM file: {e}")
        sys.exit(1)
    
    # Validate ROM
    is_valid, message = validate_gb_rom(rom_data)
    if not is_valid:
        print(f"Warning: {message}")
    
    # Get ROM info
    rom_title = get_rom_title(rom_data)
    rom_size = len(rom_data)
    chunk_size = chunk_size_kb * 1024
    
    # Split into chunks
    chunks = []
    for i in range(0, len(rom_data), chunk_size):
        chunk = rom_data[i:i + chunk_size]
        chunks.append(chunk)
    
    return chunks, rom_title, rom_size, len(chunks)

def create_lua_module(chunk_data, chunk_number, total_chunks):
    """
    Create a Lua ModuleScript that returns the chunk data
    
    Args:
        chunk_data: Binary chunk data
        chunk_number: Index of this chunk (0-based)
        total_chunks: Total number of chunks
    
    Returns:
        Lua code as string
    """
    
    # Encode to base64
    base64_data = base64.b64encode(chunk_data).decode('ascii')
    
    lua_code = f'''-- Game Boy ROM Chunk {chunk_number + 1}/{total_chunks}
-- Auto-generated by rom_chunker.py
-- This file contains base64-encoded ROM data

return "{base64_data}"
'''
    
    return lua_code

def create_roblox_loader_script(rom_title, num_chunks):
    """
    Create a Roblox LocalScript that loads all chunks
    
    Args:
        rom_title: Title of the ROM
        num_chunks: Number of chunks
    
    Returns:
        Lua code as string
    """
    
    lua_code = f'''-- Auto-generated Roblox Loader for: {rom_title}
-- Place this in StarterPlayer > StarterCharacterScripts as a LocalScript

local GameBoy = require(script.Parent.GameBoyModules.GameBoy)
local DisplayRenderer = require(script.Parent.GameBoyModules.DisplayRenderer)
local InputHandler = require(script.Parent.GameBoyModules.InputHandler)
local ROMLoader = require(script.Parent.GameBoyModules.ROMLoader)

-- Load ROM chunks from ReplicatedStorage
local romChunksFolder = game.ReplicatedStorage:WaitForChild("ROMs"):WaitForChild("{rom_title}")
local romLoader = ROMLoader.new()

print("Loading ROM chunks from ReplicatedStorage...")
local romData, message = romLoader:loadFromChunks(romChunksFolder)

if not romData then
	warn("Failed to load ROM: " .. message)
	return
end

-- Parse ROM info
local romInfo = romLoader:getInfo(romData)
print("ROM Title: " .. (romInfo.title or "Unknown"))
print("ROM Type: " .. romInfo.type)
print("ROM Size: " .. romInfo.romSize .. " KB")
print("Total Chunks Loaded: {num_chunks}")

-- Create emulator
local emulator = GameBoy.new()
emulator:loadROM(romData)

-- Create GUI
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "GameBoyEmulator"
screenGui.ResetOnSpawn = false
screenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

-- Initialize display and input
local display = DisplayRenderer.new(screenGui)
local inputHandler = InputHandler.new(emulator)
inputHandler:connect()

-- Start emulation
emulator:run()
local isRunning = true

print("Emulator started!")

-- Emulation loop
local updateConnection
updateConnection = game:GetService("RunService").Heartbeat:Connect(function()
	if not isRunning or not screenGui or not screenGui.Parent then
		if updateConnection then
			updateConnection:Disconnect()
		end
		return
	end
	
	-- Execute CPU cycles
	for i = 1, 70224 do
		emulator:step()
	end
	
	-- Update display
	display:updateFrame(emulator:getFramebuffer())
end)
'''
    
    return lua_code

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 rom_chunker.py <path_to_rom_file> [chunk_size_kb]")
        print("Example: python3 rom_chunker.py pokemon_red.gb 10")
        sys.exit(1)
    
    rom_path = sys.argv[1]
    chunk_size_kb = 10
    
    if len(sys.argv) > 2:
        try:
            chunk_size_kb = int(sys.argv[2])
        except ValueError:
            print("Error: chunk_size_kb must be an integer")
            sys.exit(1)
    
    print(f"Processing: {rom_path}")
    print(f"Chunk size: {chunk_size_kb} KB")
    
    # Split ROM into chunks
    chunks, rom_title, rom_size, num_chunks = split_rom_into_chunks(rom_path, chunk_size_kb)
    
    print(f"\nROM Information:")
    print(f"  Title: {rom_title}")
    print(f"  Size: {rom_size} bytes ({rom_size / 1024:.2f} KB)")
    print(f"  Chunks: {num_chunks}")
    
    # Create output directory structure
    output_dir = os.path.join("ROM_Chunks", rom_title)
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"\nCreating chunk files in: {output_dir}/")
    
    # Create chunk files
    for i, chunk in enumerate(chunks):
        lua_code = create_lua_module(chunk, i, num_chunks)
        chunk_file = os.path.join(output_dir, f"Chunk_{i}.lua")
        
        with open(chunk_file, 'w') as f:
            f.write(lua_code)
        
        print(f"  Created Chunk_{i}.lua ({len(chunk)} bytes, {len(lua_code)} lines of code)")
    
    # Create loader script
    loader_script = create_roblox_loader_script(rom_title, num_chunks)
    loader_file = os.path.join(output_dir, "LOADER_SCRIPT.lua")
    
    with open(loader_file, 'w') as f:
        f.write(loader_script)
    
    print(f"  Created LOADER_SCRIPT.lua")
    
    # Create setup instructions
    instructions = f'''# Instructions for {rom_title}

## Step 1: Create Folder Structure in Roblox Studio

1. Go to **ReplicatedStorage**
2. Create a Folder named **"ROMs"**
3. Inside ROMs, create a Folder named **"{rom_title}"**

## Step 2: Create ModuleScripts

Inside the "{rom_title}" folder, create {num_chunks} ModuleScripts:
- Chunk_0
- Chunk_1
- Chunk_2
- ... (up to Chunk_{num_chunks - 1})

## Step 3: Paste Chunk Code

For each chunk file:
1. Open `Chunk_X.lua` from the `{output_dir}` folder
2. Copy all the content
3. Paste it into the corresponding ModuleScript in Roblox Studio

## Step 4: Create Loader Script

1. In **StarterPlayer > StarterCharacterScripts**, create a **LocalScript**
2. Copy the content from `LOADER_SCRIPT.lua`
3. Paste it into the LocalScript

## Step 5: Run!

Play your game and the emulator will automatically load and run!

## Control Scheme

- Arrow Keys = D-Pad
- Z = A Button
- X = B Button
- Enter = Start
- Backspace = Select

---

Generated chunks: {num_chunks}
Total ROM size: {rom_size} bytes
Chunk size: {chunk_size_kb} KB
'''
    
    instructions_file = os.path.join(output_dir, "INSTRUCTIONS.md")
    with open(instructions_file, 'w') as f:
        f.write(instructions)
    
    print(f"  Created INSTRUCTIONS.md")
    
    print(f"\n✓ Done! All files created in: {output_dir}/")
    print(f"\nNext steps:")
    print(f"1. Read INSTRUCTIONS.md in the {rom_title} folder")
    print(f"2. Create folder structure in Roblox Studio")
    print(f"3. Paste chunk code into ModuleScripts")
    print(f"4. Paste loader script into LocalScript")

if __name__ == "__main__":
    main()
